version: "3.8"

services:
  mongodb:
    image: mongo:6.0.4
    container_name: healthcare-test-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=healthcare-test
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - healthcare-test-network

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: healthcare-test-app
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - USE_REAL_MONGODB=true
      - MONGO_URI_TEST=mongodb://mongodb:27017/healthcare-test
      - MONGO_DB_NAME=healthcare-test
      - JWT_SECRET=test-secret-key
      - NEXT_PUBLIC_API_URL=http://app-test:3000/api
      - NEXT_PUBLIC_WS_URL=ws://app-test:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - test-results:/app/test-results
      - coverage:/app/coverage
    command: npm run test:ci
    networks:
      - healthcare-test-network

volumes:
  mongodb_test_data:
  node_modules:
  test-results:
  coverage:

networks:
  healthcare-test-network:
    driver: bridge
